Feature/bmw 3 additional data
dalathegreat/Battery-Emulator pull request #249
Opened 2024-04-09 19:58 UTC by odlg

**What**
Additional data fetch from battery. Found additional method to fetch data that was not available before.

**Why**
Having min/max/avg cell voltage and SOH is needed to know the state and health of the battery. 

**How**
Sending specific CAN messages makes it respond a little later with requested information.

2024-04-09 20:06 UTC, dalathegreat requested changes
Very nice work! Some minor thoughts about webserver!

2024-04-09 20:06 UTC, dalathegreat commented on Software/src/devboard/webserver/webserver.cpp
> +#ifdef BMW_I3_BATTERY
We should instead have separate pages for each battery size, where additional info is displayed. I would suggest removing these lines in webserver.cpp , and we can rework this later. We want to avoid this file growing into a monster!

2024-04-09 20:06 UTC, dalathegreat commented on Software/src/devboard/webserver/webserver.h
> +#ifdef BMW_I3_BATTERY
See the comment about growing webserver

2024-04-09 20:06 UTC, dalathegreat commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +#define MAX_CAN_FAILURES 500                   // Amount of malformed CAN messages to allow before raising a warning
This define should not be needed, it is duplicated, and placed in config.h (so include that file like done in Nissan LEAF battery)

2024-04-09 20:18 UTC, odlg commented on Software/src/devboard/webserver/webserver.cpp
> +#ifdef BMW_I3_BATTERY
✔️

2024-04-09 20:18 UTC, odlg commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +#define MAX_CAN_FAILURES 500                   // Amount of malformed CAN messages to allow before raising a warning
Aarh, yes, a merge bug. Fixed.

2024-04-09 20:22 UTC, dalathegreat approved these changes

2024-04-09 20:24 UTC, dalathegreat commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +uint16_t battery_soc = 0;
consider making these `static` so no other battery tries to use the same name and get conflicts! battery_soc is quite generic :)

2024-04-10 06:18 UTC, odlg commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +uint16_t battery_soc = 0;
Fixed

2024-04-10 15:56 UTC, merged