Improvement/led handling
dalathegreat/Battery-Emulator pull request #252
Opened 2024-04-12 07:25 UTC by Cabooman

2024-04-12 13:07 UTC, dalathegreat commented on Software/USER_SETTINGS.h
> +/* Select HW - DONT TOUCH */
Since there is yet no other variant than HW_LILYGO, can we hide this from the USER_SETTINGS.h file and have it permadefined?

2024-04-12 13:07 UTC, dalathegreat commented on Software/Software.ino
> +// MyTimer task_timer_200ms(INTERVAL_200_MS);
Remove this uncommented row?

2024-04-12 14:24 UTC, Cabooman commented on Software/USER_SETTINGS.h
> +/* Select HW - DONT TOUCH */
Absolutely, I was thinking the same thing. Whenever you feel the need to write "DONT TOUCH" next to something it should probably be less visible :)

2024-04-12 14:24 UTC, Cabooman commented on Software/Software.ino
> +// MyTimer task_timer_200ms(INTERVAL_200_MS);
Yes!

2024-04-13 02:39 UTC, smaresca commented on Software/Software.ino
> +    run_event_handling();
Multiple functions invoked before this line in core_loop() may set an event and placement of run_event_handling() **here** therefore makes sense; however, is there any argument to be made for running event handling sooner?  

I think the semantics of set_event and clear_event (e.g., with the setting of bms status) mean that it's not necessary.  Just seeking confirmation.

2024-04-13 02:52 UTC, smaresca commented on Software/src/devboard/utils/value_mapping.h
> +#define CONSTRAIN(val, min, max) (MIN(max, MAX(min, val)))
probably needs a warning about side effects for sanity-preservation purposes. I can see why this is locally defined rather than rely upon platform-provided items.

Usage needs to be 
int x = function();
CONSTRAIN(x, 5, 10);
rather than
CONSTRAIN(function(), 5, 10)

This is not a complaint about current usage in this PR...just proactive acknowledgement of subtle bugs that could result.  Official Arduino docs make note for this very reason.

2024-04-13 02:56 UTC, smaresca commented on Software/src/devboard/utils/types.h
> +#ifdef FUNCTION_TIME_MEASUREMENT
Opinion: performance/time measurement macros should exist outside of a types.h

2024-04-13 03:30 UTC, smaresca requested changes
Just finished an initial read-through. I may have a comment or two as I rebase my branch against this.

2024-04-13 03:30 UTC, smaresca commented on Software/src/devboard/datalayer/datalayer.h
I suggest moving datalayer up one level (rather than nesting in devboard/ ), placing it alongside equally important include.h, system_settings.h, etc.

2024-04-13 05:33 UTC, Cabooman commented on Software/src/devboard/utils/types.h
> +#ifdef FUNCTION_TIME_MEASUREMENT
Good point, they were some last-minute scope creep so I didn't think it over properly. Moving to utils!

2024-04-13 05:33 UTC, Cabooman commented on Software/src/devboard/utils/value_mapping.h
> +#define CONSTRAIN(val, min, max) (MIN(max, MAX(min, val)))
I agree, I'll add a note. Not that I expect anyone to read it but then we've at least tried ;)

2024-04-13 05:40 UTC, Cabooman commented on Software/Software.ino
> +    run_event_handling();
Yes, placement of this technically doesn't matter, as it only updates the "system time", checks if the EE log should be written and such. Event reactions are always immediate

2024-04-13 20:25 UTC, dalathegreat commented on Software/USER_SETTINGS.h
> +//#define FUNCTION_TIME_MEASUREMENT  // Enable this to record execution times and present them in the web UI
I would add similar addition like on DEBUG_USB option `(WARNING, raises CPU load, do not use for production)`

2024-04-13 20:25 UTC, dalathegreat commented on Software/src/devboard/webserver/webserver.cpp
> +    float powerFloat = static_cast<float>(datalayer.battery.status.active_power_W);  // Convert to float
Doesn't this mean that all other batteries other than LEAF will show 0W here?

2024-04-13 20:35 UTC, dalathegreat commented on Software/src/devboard/utils/soc_scaling.cpp
> +#include "soc_scaling.h"
I feel like the SOC scaling (and SOC handling in general) might change quite a bit with the introduction of Double-Battery, so is it really worth it to add two unused files in this PR (that might be outdated quickly?)

2024-04-13 20:36 UTC, Cabooman commented on Software/USER_SETTINGS.h
> +//#define FUNCTION_TIME_MEASUREMENT  // Enable this to record execution times and present them in the web UI
Will do!

2024-04-13 20:44 UTC, Cabooman commented on Software/src/devboard/webserver/webserver.cpp
> +    float powerFloat = static_cast<float>(datalayer.battery.status.active_power_W);  // Convert to float
Yes it does, and that's of course not intended. It could get some condition for value selection but that wouldn't be reasonable. I suggest I revert the data layer "test" and make a complete transition in the next branch

2024-04-13 20:50 UTC, Cabooman commented on Software/src/devboard/utils/soc_scaling.cpp
> +#include "soc_scaling.h"
Similar as the data layer, I'd like to keep the files and "plug them in" in the next branch. It's nicely packaged so it would be easy to extend the files with a double-SOC class. We probably shouldn't mix double- and single-battery functionality in the same "location" anyway

2024-04-14 09:50 UTC, dalathegreat approved these changes
Tested out the build on my desk-setup; Holding F5 in the webserver could tank the occasional 10ms message towards 13ms, but now the furthest drift is 11ms 📉 🥳

I am approving this, but would like to test it on some batteries before we merge! 🙌

2024-04-14 12:41 UTC, merged