Bugfix: Make faulted LED solid red again 🔴
dalathegreat/Battery-Emulator pull request #263
Opened 2024-04-23 15:16 UTC by dalathegreat

### What
This PR makes the LED on the board stay on with solid red color incase we enter faulted state

### Why
Having the fault state solid red without any animations helps the user figure out that something is wrong. It is also better for colorblind users that may mistake the green from red.

### How
The rewrite for the LED handling introduced in software 5.7.1 added new animations. The fault state accidentally got animated, it should be static.

2024-04-23 17:26 UTC, Cabooman requested changes

2024-04-23 17:26 UTC, Cabooman commented on Software/src/devboard/utils/led_handler.cpp
> +          pixels.setPixelColor(0, COLOR_RED(150));  // Red LED full brightness
Here we should use LED_MAX_BRIGHTNESS as it will/might depend on the specific hw

2024-04-23 17:34 UTC, dalathegreat commented on Software/src/devboard/utils/led_handler.cpp
> +          pixels.setPixelColor(0, COLOR_RED(150));  // Red LED full brightness
Fixed in [3581465](https://github.com/dalathegreat/Battery-Emulator/pull/263/commits/35814656cd7fadfd326a385726b1cf600b7f5b1e)

2024-04-24 03:37 UTC, Cabooman approved these changes

2024-04-24 15:35 UTC, merged