Microfeature: Add uptime tracking and display
dalathegreat/Battery-Emulator pull request #268
Opened 2024-04-24 21:39 UTC by smaresca

**What**

Adds overflow-tolerant uptime tracking and reporting via webserver UI

**How**

By incorporating the very useful Uptime_Library by Yiannis Bourkelis (license compatibility verified). Header guard added locally within this project.

**Notes**
Feature requested by f1racr.

Multiple other time-oriented refinements are likely possible as benefit of having this in place (already noted by @Cabooman in discussion). This branch may be revised to account for some of those.

2024-04-25 12:42 UTC, Cabooman requested changes
Current implementation is OK, but I suggest:
- Integrating uptime for event timestamps
- Removing the example code and other things not needed in this context

2024-04-25 17:24 UTC, dalathegreat commented
The integration of timestamps for events is a bit tricker, could be done in a separate PR. I would be OK with merging this as soon as the examples folder is removed @smaresca , nice work 👍

2024-04-25 18:52 UTC, smaresca commented
> The integration of timestamps for events is a bit tricker, could be done in a separate PR. I would be OK with merging this as soon as the examples folder is removed @smaresca , nice work 👍

The examples folder is part of the upstream lib @dalathegreat . I was hesitant to make too many local modifications during import..

2024-04-26 13:01 UTC, Cabooman approved these changes

2024-04-26 19:17 UTC, merged