BMW i3: Add cellvoltage safeties and pack size autodetect
dalathegreat/Battery-Emulator pull request #279
Opened 2024-04-30 20:56 UTC by dalathegreat

### What
This PR adds automatic pack size detection, which is used to set designvoltages and check safeties

### Why
Safer operation of BMW i3 batteries

### How
We use kWh reported amount to switch between 60/94/120AH cellvoltage/packvoltage limits. Note, values needs testing, this is a good starting point!

![bild](https://github.com/dalathegreat/Battery-Emulator/assets/26695010/e067bb06-8101-4027-8902-58e30090a05c)

2024-05-01 07:23 UTC, odlg requested changes

2024-05-01 07:23 UTC, odlg commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +    datalayer.battery.info.max_design_voltage_dV = 3950;
I can not see the reason for mixing defines with values in the code. I think it should be either only defines or values in the code.

2024-05-01 14:16 UTC, dalathegreat commented on Software/src/battery/BMW-I3-BATTERY.cpp
> +    datalayer.battery.info.max_design_voltage_dV = 3950;
@odlg Thanks, fixed in e9e65de

2024-05-01 14:27 UTC, odlg approved these changes
Looks fine now :-)

2024-05-01 15:26 UTC, merged

2024-05-12 14:32 UTC, havrla commented
I'll just add how it behaves in the vehicle:

If the electricity meter reaches 0kWh, consumption by the converter drops to a minimum and driving is only possible with a step, after a while it is not even possible to drive (approx. 320V). So a dead battery - it will end the energy counter softly, a lower cell voltage hard.

If the battery is charging, it will stop when the maximum battery cell voltage is reached (4.07/4.15/4.2V). Charged is then insured by the maximum battery voltage of 392V(60Ah), 398V(94Ah), 403V(120Ah). After reaching this value, the energy counter is synchronized from above.

The size of the energy counter is continuously calibrated, but here it will be shown in practice how it will work on PV plants. Large calibrations in the vehicle require the vehicle to be put to sleep for at least 15 minutes.