Add debug functions for can fd
dalathegreat/Battery-Emulator pull request #289
Opened 2024-05-05 17:07 UTC by kukumagi

What
This PR adds settings to enable can fd debugging.

Why
To improve ease of access to can fd data in serial monitor.

How
Enabling #define DEBUG_CANFD_DATA in USER_SETTINGS.h then it starts to print out frames from can fd data stream.

2024-05-05 18:55 UTC, dalathegreat requested changes

2024-05-05 18:55 UTC, dalathegreat commented on Software/src/battery/KIA-E-GMP-BATTERY.cpp
> +#ifdef DEBUG_CANFD_DATA
Could I suggest moving this out to Software.ino instead? That way it could be used for all CAN-FD protocols. I have been thinking about doing the same for the normal CAN debug mode

2024-05-06 15:31 UTC, dalathegreat commented on Software/Software.ino
> +void debug_canfd_frame(CANFDMessage frame) {
One more suggestion, would be better if we only kept the `print_canfd_frame` function, and skipped the `debug_canfd_frame` in Software.ino!

2024-05-07 15:36 UTC, kukumagi commented on Software/Software.ino
> +void debug_canfd_frame(CANFDMessage frame) {
Merged the two functions into one.

2024-05-07 19:41 UTC, dalathegreat approved these changes

2024-05-07 19:41 UTC, merged