Feature: Add configurable limit to charge/discharge on BYD Modbus
dalathegreat/Battery-Emulator pull request #290
Opened 2024-05-06 17:36 UTC by dalathegreat

### What
This PR adds so that the values set in webserver for max charge/discharge in amps is now read by the BYD Modbus inverter protocol

### Why
To be able to tune peak power from the webui

### How

2024-05-07 16:45 UTC, Cabooman requested changes

2024-05-07 16:45 UTC, Cabooman commented on Software/src/inverter/BYD-MODBUS.cpp
> +  system_data[2] = std::min(static_cast<int>(datalayer.battery.info.total_capacity_Wh), 60000);
It would be better to cast "60000" to uint32_t since assigning an int to a uint16_t isn't preferred. Assigning a uint32_t with a maximum value of 60000 is totally OK tho

Same for the other casts in other functions

2024-05-07 16:45 UTC, Cabooman commented on Software/src/inverter/BYD-MODBUS.cpp
> +  //system_data[1] = 0;  // Id: p202 Value: 0 Scaled: 0 Comment: Always 0
Maybe these could be moved and initialized to 0 somewhere? Static variables are in most cases initialized to 0 but it could be risky to rely on compiler behavior

Same for the rest of the 0's, and also for the non-zero constant values

2024-05-07 16:45 UTC, Cabooman commented on Software/src/inverter/BYD-MODBUS.cpp
> +  static int user_configured_max_discharge_W =
Is user_configured_max_discharge_W intended to be constant? Using "static" will initialize it once and never again in subsequent function calls since there's no assignment outside of the declaration. I also prefer using unsigned types with unsigned types and not involving ints :)

Same for other variables

2024-05-07 16:45 UTC, Cabooman commented on Software/src/inverter/BYD-MODBUS.cpp
> +  memcpy(&mbPV[300], battery_data, sizeof(battery_data));
Same comment as earlier but a little different:
Perhaps the constant values including 0's could be initialized at startup? It would require some rearranging but would make this part slimmer and would also get rid of the commented assignments

2024-05-07 20:17 UTC, dalathegreat commented on Software/src/inverter/BYD-MODBUS.cpp
> +  system_data[2] = std::min(static_cast<int>(datalayer.battery.info.total_capacity_Wh), 60000);
Agreed, fixed in [293ef97](https://github.com/dalathegreat/Battery-Emulator/pull/290/commits/293ef97c7e85fbe4a5f997a9d774f568880b7dd8)

2024-05-07 20:18 UTC, dalathegreat commented on Software/src/inverter/BYD-MODBUS.cpp
> +  //system_data[1] = 0;  // Id: p202 Value: 0 Scaled: 0 Comment: Always 0
Let's save this for a bigger modbus refactoring. Restored the 0 writes in [57b580f](https://github.com/dalathegreat/Battery-Emulator/pull/290/commits/57b580f4c2e5c18d75133c0cbf499b5cfeef0d69)

2024-05-07 20:19 UTC, dalathegreat commented on Software/src/inverter/BYD-MODBUS.cpp
> +  memcpy(&mbPV[300], battery_data, sizeof(battery_data));
Same comment as above, let's save this for a bigger refactoring session. Restored the uncommented 0 writes in [57b580f](https://github.com/dalathegreat/Battery-Emulator/pull/290/commits/57b580f4c2e5c18d75133c0cbf499b5cfeef0d69)

2024-05-07 20:52 UTC, dalathegreat commented on Software/src/inverter/BYD-MODBUS.cpp
> +  memcpy(&mbPV[300], battery_data, sizeof(battery_data));
I changed my mind! Did the first p201 refactoring here: [3a640bb](https://github.com/dalathegreat/Battery-Emulator/pull/290/commits/3a640bb2b81fc0987332cdb0515b6863948d0414)

2024-05-07 20:56 UTC, dalathegreat commented
Converting to draft, I want to investigate more on how to increase performance

2024-05-10 10:40 UTC, dalathegreat commented
Ready for review, this is now extremely sped up! :)

2024-05-11 23:57 UTC, smaresca commented
Looks good to me given the PR scope. I agree with Caboom on the need/suggestions for initialization refactoring; I had the same impulses. Glad to see reduced reliance upon memcpy. For the future: configurable limit for charge/discharge being expanded elsewhere.

2024-05-12 07:51 UTC, Cabooman approved these changes
LGTM! There's always small stuff to tweak but iterations are king

2024-05-12 07:51 UTC, Cabooman commented on Software/src/inverter/BYD-MODBUS.cpp
> +  mbPV[202] = std::min(datalayer.battery.info.total_capacity_Wh, static_cast<uint32_t>(60000));
Here and in other places: 
Do you get a compile error if you don't use the static cast? A solution that's more easy on the eyes could be to simply try stating the constant value as "60000u" instead

2024-05-12 16:41 UTC, dalathegreat commented on Software/src/inverter/BYD-MODBUS.cpp
> +  mbPV[202] = std::min(datalayer.battery.info.total_capacity_Wh, static_cast<uint32_t>(60000));
That works! Fixed in [6eb518a](https://github.com/dalathegreat/Battery-Emulator/pull/290/commits/6eb518ae77063ae0598b3b27c12d1dc4ae5ddd5c)

2024-05-12 16:47 UTC, merged