Add basic GitHub Issue/PR templates
dalathegreat/Battery-Emulator pull request #456
Opened 2024-09-12 12:23 UTC by obbardc

### What
This PR implements GitHub templates for new issues/PRs.

### Why
This is so I don't annoy @dalathegreat when opening PRs which do not follow the standard format ;-).

### How
Following github documentation to create the templates.

PS: Feel free to improve by editing the commit or commenting here. I will collect all changes.

2024-09-12 14:18 UTC, obbardc commented
I thought about having separate templates for bug/feature request too, which could add labels to the resultant issue.

2024-09-12 19:51 UTC, lenvm commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] CI tests pass
This information is already included in the PR. Having it also in the PR description is duplicating the information, and adds redundant work for the PR creator.

2024-09-15 19:19 UTC, dalathegreat commented on .github/PULL_REQUEST_TEMPLATE.md
> +
Remove this line to make it symmetric

2024-09-15 19:26 UTC, dalathegreat requested changes

2024-09-15 19:26 UTC, dalathegreat commented on .github/ISSUE_TEMPLATE.md
> +### Expected Behavior
Like @amarofarinha suggested, we should add one field for Settings

### Settings
    Software Version
    Battery type
    Inverter communication protocol
    Hardware used for Battery-Emulator (LilyGo, Stark CMR, Custom)
    CONTACTOR_CONTROL (yes/no)
    DUAL_CAN (yes/no)
    WEBSERVER (yes/no)
    MQTT (yes/no)

2024-09-20 15:41 UTC, obbardc commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] CI tests pass
Actually, I removed it. Can always be added later if it helps.

2024-09-20 18:46 UTC, dalathegreat approved these changes

2024-09-20 18:46 UTC, merged