Add Support for External Button and Web-Based Equipment Stop Functionality
dalathegreat/Battery-Emulator pull request #506
Opened 2024-10-02 02:05 UTC by amarofarinha

### What
This PR implements both an external equipment stop button and a web-based emergency stop, allowing for full system shutdown in critical situations. Both options halt charge and discharge operations, open battery contactors (if controlled by the battery), and stop all CAN communications.

### Why
The idea for this enhancement originated from @StarkJohan, who provided valuable feedback and insights throughout our discussions. The primary motivation for adding these features is to introduce additional safety mechanisms to the emulator, ensuring that emergency shutdowns can be triggered swiftly via either a physical button or the web interface. These options enhance the safety and responsiveness of the system in case of a critical failure or emergency.

This PR strengthens the emulator's emergency handling capabilities by introducing redundant, user-friendly methods to stop operations in emergency scenarios.

### How
Added support for an external equipment stop button connected to a GPIO pin (EQUIPMENT_STOP_PIN).
Integrated web-based emergency stop control to trigger the same shutdown functionality.
Introduced two modes for button functionality:

- TOGGLE_SWITCH: The button directly reflects its physical state (state ON/OFF). 
- PERSISTENT_ACTIVATION_SWITCH: Implements a short/long press mechanism for activation and reset. The state is persisted between reboots.

Activation/deactivation via the web interface is possible allowing the system to resume.

when in EQUIPMENT STOP:

- Halts all charging and discharging operations.
- Stops all CAN communications.
- Opens battery contactors (if controlled by the emulator).

On boot, if an emergency button is configured, its state will take precedence for the emulator. This functionality can be used with both physical buttons and the web server. If no physical button is defined, the state set via the web server will persist across reboots. I believe this approach covers most of your suggestions, although it’s not possible to accommodate all opinions. I consider this a solid solution, which can always be improved or modified in the future.

2024-10-02 04:21 UTC, nagyrobi commented
Long press is not necessarily a good idea.

For this task, an emergency stop button is appropriate, which, when pressed, stays in pressed-in state until being released by a different movement (like rotating it).

With an emergency stop button, you are in stopped/emergency state while it's being pressed, and can only resume to normal when released.

2024-10-02 06:54 UTC, nagyrobi commented on Software/src/devboard/hal/hw_lilygo.h
> +#error EQUIPMENT_STOP_BUTTON and DUAL_CAN cannot coexist due to overlapping GPIO pin usage
No more free pins left on LilyGo?

2024-10-02 08:19 UTC, StarkJohan commented on Software/src/devboard/hal/hw_lilygo.h
> +#error EQUIPMENT_STOP_BUTTON and DUAL_CAN cannot coexist due to overlapping GPIO pin usage
No, the lilygo has a limited amount of exposed GPIO.

2024-10-02 08:25 UTC, obbardc requested changes

2024-10-02 08:25 UTC, obbardc commented on Software/Software.ino
> +  //allways get the emergency stop status
```suggestion
  // Always get the emergency stop status
```

2024-10-02 08:25 UTC, obbardc commented on Software/Software.ino
> +  datalayer.system.settings.equipment_stop_active = temp;
why not just

```
  datalayer.system.settings.equipment_stop_active = settings.getBool("EMERGENGY_STOP", false);
```
then we can also remove the variable temp ?

2024-10-02 08:25 UTC, obbardc commented on Software/Software.ino
> +    settings.putBool("EMERGENGY_STOP", datalayer.system.settings.equipment_stop_active);
prefer an enum/define for this to avoid mistyping.

also it is spelt wrong `EMERGENCY`

2024-10-02 08:25 UTC, obbardc commented on Software/Software.ino
> +  temp = settings.getBool("EMERGENGY_STOP", false);
spell check `EMERGENCY`

2024-10-02 08:25 UTC, obbardc commented on Software/USER_SETTINGS.h
> +//#define EQUIPMENT_STOP_BUTTON      // Enable this to have a emergengy/equipment stop button connected to board
```suggestion
//#define EQUIPMENT_STOP_BUTTON      // Enable this to allow an emergency/equipment stop button connected to the Battery-Emulator to disengage the battery
```

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/hal/hw_stark.h
> +// Equipment stop pin
Can you call it EMERGENCY throughout ?

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/safety/safety.cpp
> +  //fist handle emergency stop / resume
```suggestion
  // First handle emergency stop / resume
```

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/safety/safety.cpp
> +
additional line which can go away

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/safety/safety.cpp
> +
additional line

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/utils/events.cpp
> +      return "ERROR: EMERGENCY STOP ACTIVATED!!!";
Doesn't follow other errors

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/webserver/webserver.cpp
> +  server.on("/estop", HTTP_GET, [](AsyncWebServerRequest* request) {
can we call the endpoint `/emergencyStop` to match other endpoints ?

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/webserver/webserver.cpp
> +          ">EQUIPMENT STOP</button><br/>";
use `EMERGENCY`

2024-10-02 08:25 UTC, obbardc commented on Software/src/devboard/webserver/webserver.cpp
> +          ">RESUME FROM EQUIPMENT STOP</button><br/>";
EMERGENCY

2024-10-02 08:27 UTC, StarkJohan commented on Software/src/devboard/webserver/webserver.cpp
> +          ">RESUME FROM EQUIPMENT STOP</button><br/>";
EQUIPMENT STOP! @dalathegreat  :-)

2024-10-02 08:28 UTC, nagyrobi commented
> what about having configurable behaviors?

Good!

2024-10-02 10:28 UTC, dalathegreat commented
I agree with @nagyrobi , most big red e-stop switches latch once you press them. This is good behaviour, which at the same time prevents the system from accidentally starting operating after a reboot (since the request for e-stop is still active).

I have encountered quite a few e-stop designs over the years, and the majority work this way.

Having us only look at the GPIO state for the E-stop (which **needs** to be a NC circuit to prevent wire break from hindering operation of the switch) also takes out the need to store the e-stop to persistent memory. Since rebooting the emulator with the e-stop engaged will result in it going straight into stopped state.

2024-10-02 14:24 UTC, nagyrobi commented
I'm also worried about the [hard exclusion of the other features](https://github.com/dalathegreat/Battery-Emulator/pull/506#discussion_r1783916416) on LilyGo, just because the limited amount of exposed GPIO. Is the SD card used? There are 4 more GPIOs in the SD card socket. I agree they can't be easily accessed, but one could still manage to use one of them together with the other features. The GPIOs should be freely configurable without having to alter the rest of the code too heavily...

2024-10-02 14:27 UTC, nagyrobi commented
> Alternatively, we could consider giving the physical button priority over the web interface, meaning that if the button is activated, it wouldn’t be possible to deactivate it via the web interface. What would be the best approach in the schenario of a latched button?

Could be completely two different safety features. One is software stop, and the other just hardware stop. Shouldn't be related to each other. The hardware stop's status should just be shown in the web interface. One should not interfere with each other. Eg. releasing the button shouldn't release the software stop (someone physically at the device may not be aware that somebody else is remotely working and shouldn't mess the state remotely set).

2024-10-02 14:51 UTC, BEMSman commented
Shouldn’t the web interface be the final reset that would only provide reset after E-Stop have been reset locally.

 

From: H. Árkosi Róbert ***@***.***> 
Sent: 02 October 2024 15:28
To: dalathegreat/Battery-Emulator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [dalathegreat/Battery-Emulator] Add Support for External Equipment Stop Button and Web-Based Emergency Stop to Battery Emulator (PR #506)

 

Alternatively, we could consider giving the physical button priority over the web interface, meaning that if the button is activated, it wouldn’t be possible to deactivate it via the web interface. What would be the best approach in the schenario of a latched button?

Could be completely two different safety features. One is software stop, and the other just hardware stop. Shouldn't be related to each other. The hardware stop's status should just be shown in the web interface. One should not interfere with each other. Eg. releasing the button shouldn't release the software stop (someone physically at the device may not be aware that somebody else is remotely working and shouldn't mess the state remotely set).

—
Reply to this email directly, view it on GitHub <https://github.com/dalathegreat/Battery-Emulator/pull/506#issuecomment-2388794685> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ASBCYAUFUW43DYIEQL7MZGLZZP7IRAVCNFSM6AAAAABPGXYCJOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBYG44TINRYGU> .
You are receiving this because you are subscribed to this thread.  <https://github.com/notifications/beacon/ASBCYAUJ5WK3ET6QYTU6XGDZZP7IRA5CNFSM6AAAAABPGXYCJOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUOMIOT2.gif> Message ID: ***@***.*** ***@***.***> >

2024-10-02 14:53 UTC, StarkJohan commented
> I'm also worried about the [hard exclusion of the other features](https://github.com/dalathegreat/Battery-Emulator/pull/506#discussion_r1783916416) on LilyGo, just because the limited amount of exposed GPIO. Is the SD card used? There are 4 more GPIOs in the SD card socket. I agree they can't be easily accessed, but one could still manage to use one of them for this, together with the other features. The GPIOs should be freely configurable without having to alter the rest of the code too heavily...

Most user will not max out the GPIO on the lilygo. Changing the configuration of the pins is very easy in the HAL. 
For those who need more GPIOs there are multiple options. I don't see the limited GPIOs as a reason to not implement excellent safety feartures.

2024-10-03 08:59 UTC, dalathegreat commented on Software/USER_SETTINGS.cpp
> +//TOGGLE_SWITCH                - activated while pressed, deactivated when released, button state is reflected in the emulator state
We should use simple understandable terms here, my suggestion

//LATCHING_SWITCH       - Normally closed (NC), latching switch. When pressed it activates e-stop
//MOMENTARY_SWITCH - Short press to activate e-stop, long 5s press to deactivate. E-stop is persistent between reboots

However the more I think about it, I really would recommend dropping support for momentary_switch...

2024-10-03 09:28 UTC, StarkJohan commented on Software/USER_SETTINGS.cpp
> +//TOGGLE_SWITCH                - activated while pressed, deactivated when released, button state is reflected in the emulator state
I don't mind the momentary switch support, it's the reset function that need to be very safe and obvious. I don't love the long press but if it's kept, it needs to be rather long.

2024-10-03 09:55 UTC, dalathegreat commented
Sorry for joining this review so late, but I'd like to challenge the need to trigger e-stop via the webserver.

To me it seems like we are using the equipment stop terminology wrong in the Webserver. From the Webserver, it makes sense to either "Pause", or "Open Contactors". Can we rename this in the Webserver?

2024-10-03 09:55 UTC, dalathegreat commented
I am still also not sure about the benefit of handling a recovery from an "Open contactor" press. To me it makes more sense to latch this, and require a reboot to get out of it.

2024-10-03 09:56 UTC, dalathegreat commented
Same goes with the storing to persistent memory. What are we trying to prevent here? Someone opens contactors via webinterface, and then accidentally restarting, and it proceeds to operate? Feels like a very niche scenario that we dont need to consider?

2024-10-03 10:11 UTC, StarkJohan commented
> Same goes with the storing to persistent memory. What are we trying to prevent here? Someone opens contactors via webinterface, and then accidentally restarting, and it proceeds to operate? Feels like a very niche scenario that we dont need to consider?

To me the scenario of someone pausing/stopping and counting on this being persistent is a good reason to keep the persistence after a power outage or other accidental reboot.

2024-10-03 11:40 UTC, dalathegreat approved these changes

2024-10-03 13:08 UTC, merged