Add new battery implementation "Renault Twizy" (LV)
dalathegreat/Battery-Emulator pull request #537
Opened 2024-10-14 14:05 UTC by M4GNV5

### What
This PR implements the CAN bus protocol of Renault Twizy Batteries.
~~Not yet tested with real hardware. Also includes some `TODOs` where I was unsure about the correct way to implement something. A review would be much appreciated.~~
Tested and reviewed

### Why
See: #536 

### How
This is just a straightforward decoder for CAN messages sent by a Renault Twizy BMS. The protocol is [documented by the Twizy community here](https://docs.google.com/spreadsheets/d/1gOrG9rnGR9YuMGakAbl4s97a6irHF6UNFV1TS5Ll7MY/edit?gid=0#gid=0).
For now we do not wake up the battery. For a still built-in battery one can simply turn on the vehicle. For a plain battery (without vehice) this is a TODO.

2024-10-14 14:08 UTC, obbardc requested changes
small bits

2024-10-14 14:08 UTC, obbardc commented on Software/USER_SETTINGS.h
>  //#define RENAULT_KANGOO_BATTERY
Need to add it to github CI to be built.

2024-10-14 14:08 UTC, obbardc commented on Software/src/battery/RENAULT-TWIZY.cpp
> +int16_t min_value(int16_t *entries, size_t len) {
linebreak above

2024-10-14 14:08 UTC, obbardc commented on Software/src/battery/RENAULT-TWIZY.cpp
> +  }
Need to set datalayer to new values & also print to USB serial port.

2024-10-14 17:21 UTC, dalathegreat commented on Software/USER_SETTINGS.h
>  //#define RENAULT_KANGOO_BATTERY
If the code is not yet tested on real hardware, best to leave it out of CI until it is stable

2024-10-14 17:22 UTC, obbardc commented on Software/USER_SETTINGS.h
>  //#define RENAULT_KANGOO_BATTERY
But CI is there to make sure the main branch builds ? We could get into a position where there are commits which break the build.

2024-10-14 17:26 UTC, dalathegreat commented on Software/src/battery/RENAULT-TWIZY.cpp
> +
Suggestion to add amount of cells to setup_battery, example from 96S LEAF;

`datalayer.battery.info.number_of_cells = 96;`

2024-10-14 17:26 UTC, dalathegreat commented on Software/src/battery/RENAULT-TWIZY.cpp
> +  }
Datalayer seems to be set already. Skip printing to USB serial port, we will remove that in the future and promote the "More battery info" page

2024-10-14 17:26 UTC, dalathegreat commented on Software/src/battery/RENAULT-TWIZY.cpp
> +
To get the cellmonitor page working, add the `cellvoltages_mV` array also to the datalayer, example code;

```
          //Map all cell voltages to the global array
          memcpy(datalayer.battery.status.cell_voltages_mV, battery_cell_voltages, 96 * sizeof(uint16_t));
```

2024-10-14 17:28 UTC, obbardc commented on Software/src/battery/RENAULT-TWIZY.cpp
> +  }
Oh, OK !

2024-10-14 17:28 UTC, dalathegreat commented on Software/USER_SETTINGS.h
>  //#define RENAULT_KANGOO_BATTERY
Not possible to break the normal builds. But yes, it is possible to break the Twizy, before the Twizy is working :)

2024-10-15 07:46 UTC, M4GNV5 commented on Software/USER_SETTINGS.h
>  //#define RENAULT_KANGOO_BATTERY
I was able to compile it successfully using the `arduino-cli`. I have not yet received my inverter, but I will make some tests wether the values are read correctly from the Twizy CAN bus.

2024-10-15 08:34 UTC, dalathegreat commented on Software/USER_SETTINGS.h
> +#define RENAULT_TWIZY_BATTERY
Before merging, uncomment the RENAULT_TWIZY_BATTERY from the USER_SETTINGS.h file, otherwise builds wont pass

2024-10-15 08:36 UTC, dalathegreat reviewed
LGTM! Nice starting point for Twizy!

2024-10-15 14:22 UTC, dalathegreat approved these changes

2024-10-15 14:27 UTC, M4GNV5 commented
I made some successfull tests of the full setup utilizing the Twizy battery protocol and the pylontech LV inverter side.
So far I do not have a real inverter (waiting for delivery), but I managed to dump the produced CAN messages using an USB-CAN adapter.
Below some pictures. The bugs I found during testing have already been commited & approved above. From my side this PR is ready for merging

![photo_2024-10-15_16-25-41](https://github.com/user-attachments/assets/e5d3ca1a-f444-4f1f-9ec8-2d27d78f7b82)

![Screenshot from 2024-10-15 16-06-01](https://github.com/user-attachments/assets/3a902681-405c-480f-861a-f56c6d0b3f86)

![Screenshot from 2024-10-15 14-39-02](https://github.com/user-attachments/assets/5cbd0315-18a9-4a42-8604-ffeeddb3c0b1)

![photo_2024-10-15_16-25-42](https://github.com/user-attachments/assets/d93641b3-b63f-4599-b4dd-62d60ab2f6dc)

2024-10-15 15:32 UTC, dalathegreat commented
Amazing work @M4GNV5 :raised_hands: 

Lets merge this, and continue in smaller PRs if needed! You can join the Discord via this link: https://discord.gg/amAu64Mu

2024-10-15 15:33 UTC, merged

2024-11-22 21:25 UTC, M4GNV5 commented
Just in case anyone ever finds this PR wanting to use a Twizy Battery for battery storage.
According to [this schematics](https://github.com/dexterbg/Twizy-Virtual-BMS/blob/master/extras/Twizy-BMS-wiring-scheme.pdf) the connector next to the sevcon HV connector has several pins directly controling the relais for delivering the full battery voltage to three different outputs:

![image](https://github.com/user-attachments/assets/d3536a7b-3a5c-4dd9-9b67-4d4c21400c26)