kostal: more debug output to get better understanding of temporal behaviour
dalathegreat/Battery-Emulator pull request #644
Opened 2024-11-27 19:28 UTC by lewurm

Example:
```
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[28357 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[29177 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
[29997 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[30817 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[31637 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[32458 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[33278 ms] RX (dropped): 07 63 FF 02 FF 29 5E 02 16 00
FAKE Values going to inverter
SOH%: 99% , SOC%: 52% , Voltage: 370V , Max discharge power: 5000W , Max charge power: 5000W , Max temp: 6°C , Min temp: 5°C , Max cell voltage: 3596mV , Min cell voltage: 3500mV
[34100 ms] RX: 09 62 FF 02 FF 29 4A 08 23 00
[34100 ms] TX: 06 E2 FF 02 FF 29 01 08 A2 43 E4 70 8A 5C B5 02 D3 01 01 05 C8 41 C2 18 01 03 59 42 01 01 01 02 05 02 A0 01 01 02 2B 00
```

2024-11-28 04:12 UTC, gwk1 commented on Software/src/inverter/KOSTAL-RS485.h
> +#endif
While we have still heavy debugging going on, i prefer keeping DEBUG_KOSTAL_RS485_DATA and DEBUG_VIA_USB separated.

But that drop dropped is good, as i just figured out, that we must replace zero bytes of RX frame before rx processing, as otherwise we don't process eg. this: if (RS485_RXFRAME[6] == 0x5E) when RXFRAME[7] is 0x00 

Also rx frame length may be more than 10 bytes, as there is sent EPOCH timestamp on one frame (actually never seen that, but seen on BYD code that)

2024-11-28 21:36 UTC, lewurm commented on Software/src/inverter/KOSTAL-RS485.h
> +#endif
> But that drop dropped is good, as i just figured out, that we must replace zero bytes of RX frame before rx processing, as otherwise we don't process eg. this: if (RS485_RXFRAME[6] == 0x5E) when RXFRAME[7] is 0x00

Yes, I'm handling that in my WIP branch: https://github.com/lewurm/Battery-Emulator/blob/1df27f4444ec0cfac8822256208db3e5ff780c06/Software/src/inverter/KOSTAL-RS485.cpp#L244-L249 and https://github.com/lewurm/Battery-Emulator/blob/1df27f4444ec0cfac8822256208db3e5ff780c06/Software/src/inverter/KOSTAL-RS485.cpp#L492-L497

But I don't want to submit that change just yet, because apparently some people have success with the _current_ state and I want to understand _why_ by adding additional logging.  I suspect that it works by chance, because we send the right answer after a timeout: https://github.com/dalathegreat/Battery-Emulator/blob/4232da8aec8e06d5ecf34d77fe0ffe0f8e3f697f/Software/src/inverter/KOSTAL-RS485.cpp#L266-L268

> Also rx frame length may be more than 10 bytes, as there is sent EPOCH timestamp on one frame (actually never seen that, but seen on BYD code that)

That should be covered by the `dump_rs485_data_rx(" (!RX_allow)");` case, at least it would print it in several steps then.  But indeed, I haven't seen it in any traces yet.

2024-12-02 18:29 UTC, lewurm commented
@dalathegreat this has been tested on a bmw i3+kostal setup. are you fine with the non-kostal changes?

2024-12-12 20:37 UTC, lenvm commented
@lewurm, to get this PR approved more quickly, please remove the changes that are done in the battery file `Software/src/battery/BMW-I3-BATTERY.cpp`, and only leave the changes related to Kostal inverter.

2025-01-07 18:01 UTC, dalathegreat requested changes

2025-01-07 18:01 UTC, dalathegreat commented on Software/Software.ino
> +  Serial.print("[");
Suggestion to replace all #ifdef DEBUG_VIA_USB into #ifdef DEBUG_LOG

And also all Serial.print into logging.print

2025-01-08 20:59 UTC, lewurm commented
Thanks! Please have another look @lenvm and @dalathegreat

2025-01-12 09:59 UTC, dalathegreat approved these changes
Approved. Hope this helps Kostal!

2025-01-12 09:59 UTC, merged