Change web based CAN log file format to CANdump
dalathegreat/Battery-Emulator pull request #655
Opened 2024-12-03 09:14 UTC by mvgalen

### What
Change web based CAN log format to CANdump format.
Improve performance by removing unnecessary strncat and strlens.

### Why
Make logfiles directly compatible with SavvyCAN.

### How
Slightly changed format. 
Tested downloaded file with SavvyCAN

2024-12-03 09:27 UTC, obbardc requested changes

2024-12-03 09:27 UTC, obbardc commented on Software/Software.ino
> +    if (offset + 128 > sizeof(datalayer.system.info.logged_can_messages)) {
style nit: move size variable before the length check

2024-12-03 09:27 UTC, obbardc commented on Software/Software.ino
> +    size_t message_string_size = sizeof(datalayer.system.info.logged_can_messages);
style nit: declare where other variables are declared, at the top of the block

2024-12-03 09:27 UTC, obbardc commented on Software/Software.ino
> +    char *message_string = datalayer.system.info.logged_can_messages;
would it be better to copy into the string e.g sprintf ?

2024-12-03 09:27 UTC, obbardc commented on Software/Software.ino
> +    offset += snprintf(message_string + offset, message_string_size - offset, "\n");
perhaps `\r\n` for windows users compatibility in notepad ?

2024-12-03 09:30 UTC, mvgalen commented on Software/Software.ino
> +    if (offset + 128 > sizeof(datalayer.system.info.logged_can_messages)) {
Sorry, I am afraid I don't understand your suggestion. Can you show the changed code?

2024-12-03 09:31 UTC, obbardc commented on Software/Software.ino
> +    if (offset + 128 > sizeof(datalayer.system.info.logged_can_messages)) {
```suggestion
    if (sizeof(datalayer.system.info.logged_can_messages) > offset + 128) {
```
looks cleaner to me.

2024-12-03 09:36 UTC, mvgalen commented on Software/Software.ino
> +    size_t message_string_size = sizeof(datalayer.system.info.logged_can_messages);
Ok.

2024-12-03 09:37 UTC, mvgalen commented on Software/Software.ino
> +    char *message_string = datalayer.system.info.logged_can_messages;
What do you mean? Nothing is copied here? snprintf's are below this block.

2024-12-03 09:39 UTC, mvgalen commented on Software/Software.ino
> +    offset += snprintf(message_string + offset, message_string_size - offset, "\n");
Do you really think this is necessary? The newer windows wordpad also natively supports only \n.

2024-12-03 09:41 UTC, obbardc commented on Software/Software.ino
> +    char *message_string = datalayer.system.info.logged_can_messages;
Sorry. misread.

2024-12-03 09:41 UTC, obbardc commented on Software/Software.ino
> +    offset += snprintf(message_string + offset, message_string_size - offset, "\n");
No, that's fine :-) Just mentioned it as something minor to think about.

2024-12-03 09:56 UTC, mvgalen commented on Software/Software.ino
> +    if (offset + 128 > sizeof(datalayer.system.info.logged_can_messages)) {
Hmm, I get your point, but at the same time it seems less intuitive, since you place the comparator in the wrong direction ( > vs. < ). I definitively find it easier to read the offset+value is greater than the size.

2024-12-03 10:02 UTC, obbardc commented on Software/Software.ino
> +    if (offset + 128 > sizeof(datalayer.system.info.logged_can_messages)) {
that's fine. :-)

2024-12-03 14:30 UTC, obbardc approved these changes

2024-12-03 15:06 UTC, mvgalen commented
@obbardc is anything still blocking review approval?

2024-12-03 21:34 UTC, dalathegreat approved these changes
LGTM! Now we just need to update the can-logging wiki page to explain the format

2024-12-04 05:56 UTC, mvgalen commented
I will update the wiki later this morning.

Op di 3 dec. 2024 22:35 schreef Daniel Öster ***@***.***>:

> ***@***.**** approved this pull request.
>
> LGTM! Now we just need to update the can-logging wiki page to explain the
> format
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dalathegreat/Battery-Emulator/pull/655#pullrequestreview-2476800786>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFVJXN2JTKVBSJW5BHEHET2DYPYVAVCNFSM6AAAAABS5JPLH6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZWHAYDANZYGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-04 09:26 UTC, merged