Feature: Add periodic BMS power reset
dalathegreat/Battery-Emulator pull request #706
Opened 2024-12-29 11:57 UTC by dalathegreat

### What
This PR implements a periodic BMS reset. It achieves this by toggling a GPIO pin every 24h. This 3.3V pin can be used to control the 12V power going into the BMS via an SSR or other type of relay.

### Why
Some automotive BMSes like the Nissan LEAF BMS does not work well when powered on continously. According to OEM specs, a powercycle is required every 24hours to keep the BMS working as intended. Failure to reset the BMS can cause SOC% to drift overtime, as reported in #86 

### How
We add a new user configurable feature in the USER_SETTINGS, called `PERIODIC_BMS_RESET`. When this is enabled, a GPIO pin (See the HAL file for your hardware to see which pin), will be toggled ON upon start, and after 24 hours it will turn off for 30s. When the power is cut to this pin, the emulator is put into Paused state, meaning no CAN messages will be sent towards the battery, and the charge/discharge limits will go to 0W. After the 30 seconds have passed, power is turned back on to the pin, and the emulator is unpaused.

2024-12-30 15:15 UTC, No-Signal commented
@dalathegreat it would be great to have an option to trigger this remotely via MQTT or an HTTP post as well as a timer.

In my case I'd like to restart the BMS during the overnight window of cheap electric where I normally charge the batteries and expect others would like to do similar.

Let me know what you think and if you want to get the current version out first as happy to submit a PR.

2024-12-30 22:52 UTC, dalathegreat commented
Sounds good @No-Signal , we can do it in a PR after this is in. At the same time, forcing a balance charge will also be something that will be nice to have controllable via MQTT, as implemented in PR #718

2025-01-02 12:33 UTC, mvgalen commented on Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
> +    setBatteryPause(true, true, false, false);
This might not be ideal for batteries with internal contactors like MEB. They need to be opened before shutting down the BMS. I should look into what the current behavior is, equipment stop may already gracefully open the contactors.

2025-01-02 12:35 UTC, dalathegreat commented on Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
> +    setBatteryPause(true, true, false, false);
Is there any indication that MEB needs periodic reset? Mainly this whole PR is only based on LEAF batteries needing this

2025-01-02 12:51 UTC, mvgalen commented on Software/src/devboard/hal/hw_lilygo.h
> +#define BMS_POWER 18  // Note, this pin collides with CAN add-ons and Chademo
Wouldn't it be nice to change it depending on if CAN_ADDON or CONTACTOR_CONTROL are defined? That would mean it would not always be the same pin, but would make is available in more scenario's.

2025-01-02 12:53 UTC, mvgalen requested changes
Added two comments, the rest looks good to me.

2025-01-02 12:53 UTC, mvgalen commented on Software/src/communication/contactorcontrol/comm_contactorcontrol.cpp
> +    setBatteryPause(true, true, false, false);
I don't know yet. Lets keep this section as it is for now.

2025-01-02 15:38 UTC, dalathegreat commented on Software/src/devboard/hal/hw_lilygo.h
> +#define BMS_POWER 18  // Note, this pin collides with CAN add-ons and Chademo
Yes, BUT, since the GPIO structure is getting quite complicated on the LilyGo, I personally think it is better that the end user assumes some planning responsibility here, and manages it to another pin if they have some special combination. For the LEAF (which this feature is for), the pins dont collide with Automatic contactor control, which is the most important factor.

2025-01-02 20:36 UTC, mvgalen commented on Software/src/devboard/hal/hw_lilygo.h
> +#define BMS_POWER 18  // Note, this pin collides with CAN add-ons and Chademo
Ok, makes sense. I do think it would be best if we dictate (via ifdefs) the possible options, but let's wait until somebody asks for it.

2025-01-02 20:37 UTC, mvgalen approved these changes
LGTM.

2025-01-02 21:43 UTC, merged

2025-02-18 19:53 UTC, ruffieuxh commented
Cool! Many thanks!
Got a question: How do I see, if the feature works without standing by the battery when it happens? Is there an event logged?